
# # python get_augment_label.py augment_data.split="random_cv1" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="random_cv2" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="random_cv3" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="random_cv4" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="random_cv5" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="scaffold_seed1" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="scaffold_seed2" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="scaffold_seed3" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="scaffold_seed4" augment_data.name="AID1798"
# # python get_augment_label.py augment_data.split="scaffold_seed5" augment_data.name="AID1798"


# python get_augment_label.py augment_data.split="random_cv1" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="random_cv2" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="random_cv3" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="random_cv4" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="random_cv5" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="scaffold_seed1" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="scaffold_seed2" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="scaffold_seed3" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="scaffold_seed4" augment_data.name="AID488997"
# python get_augment_label.py augment_data.split="scaffold_seed5" augment_data.name="AID488997"

# python get_augment_label.py augment_data.split="random_cv1" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="random_cv2" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="random_cv3" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="random_cv4" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="random_cv5" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="scaffold_seed1" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="scaffold_seed2" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="scaffold_seed3" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="scaffold_seed4" augment_data.name="AID485290"
# python get_augment_label.py augment_data.split="scaffold_seed5" augment_data.name="AID485290"


# python get_augment_label.py augment_data.split="random_cv1" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="random_cv2" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="random_cv3" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="random_cv4" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="random_cv5" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="scaffold_seed1" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="scaffold_seed2" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="scaffold_seed3" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="scaffold_seed4" augment_data.name="AID463087"
# python get_augment_label.py augment_data.split="scaffold_seed5" augment_data.name="AID463087"

# python get_augment_label.py augment_data.split="random_cv1" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="random_cv2" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="random_cv3" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="random_cv4" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="random_cv5" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="scaffold_seed1" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="scaffold_seed2" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="scaffold_seed3" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="scaffold_seed4" augment_data.name="AID2689"
# python get_augment_label.py augment_data.split="scaffold_seed5" augment_data.name="AID2689"
